### Labeling

필기체숫자사진받아서 각 숫자 라벨링

In [7]:
import cv2
import numpy as np

src = cv2.imread('number.jpeg', cv2.IMREAD_GRAYSCALE)
_, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_OTSU)
cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)
dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

print(cnt)
print(labels)
print(labels)
print(stats)
print(centroids)

for i in range(1,cnt):
    (x, y, w, h, area) = stats[i]
    # 픽셀 10개 미만이면 bounding box 예외처리
    if area < 10:
        continue
    cv2.rectangle(dst, (x, y, w, h), (0, 0, 255), 2)


cv2.imshow('src',src)
cv2.imshow('src_bin',src_bin)
cv2.imshow('dst',dst)

cv2.waitKey()
cv2.destroyAllWindows()

56
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[    45     78    680    427  24296]
 [     0      0    750    563 386360]
 [   334     88     21     33    491]
 [   340     90      1      1      1]
 [   300     95      1      1      1]
 [   333     96      3      4      5]
 [   683    135     18     25    264]
 [   167    138     10     12     87]
 [    84    152      9     11     74]
 [   167    156      7     11     60]
 [   598    166     18     16    227]
 [   260    171     15     19    143]
 [   372    178     15     14    161]
 [   325    181      1      1      1]
 [   329    182      1      1      1]
 [   118    184     12     10     90]
 [   161    184     12     22    173]
 [   471    195     15     12    130]
 [   556    207     19     13    196]
 [   463    212     14     18    18

농구/야구 사진 받아 공을 연두색 박스로 그리고 전체사진을 연속적으로 줄여가며 그리기

In [19]:
#ㅎ ㅏ...안찾아진다 공
import cv2
import numpy as np
import math

def setLabel(img, pts, label):
    (x, y, w, h) = cv2.boundingRect(pts)
    pt1 = (x,y)
    pt2 = (x + w, y + h)
    cv2.rectangle(img, pt1, pt2, (0, 255, 0), 1)
    cv2.putText(img, label, pt1, cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))
    
img = cv2.imread('basketball.jpg', cv2.IMREAD_COLOR)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_thr = cv2.adaptiveThreshold(img_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,15,1)
cv2.imshow('thr', img_thr)

contours, _ = cv2.findContours(img_thr, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for pts in contours:
    #if cv2.contourArea(pts) < 10:  #  너무 작으면 무시
     #   continue
    
    approx = cv2.approxPolyDP(pts, cv2.arcLength(pts, True)*0.05, True)
    vtc = len(approx)
    
    if cv2.isContourConvex(pts) and vtc != 3 and vtc != 4:
        length = cv2.arcLength(pts, True)
        area = cv2.contourArea(pts)
        ratio = 4 * math.pi * area / (length * length)
        
        if ratio > 0.8:
            setLabel(img, pts, 'ball')
            
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [39]:
import cv2
import numpy as np
import math

def setLabel(img, pts, label):
    (x, y, w, h) = cv2.boundingRect(pts)
    pt1 = (x,y)
    pt2 = (x + w, y + h)
    cv2.rectangle(img, pt1, pt2, (0, 255, 0), 1)
    cv2.putText(img, label, pt1, cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))
    
img = cv2.imread('basketball.jpg', cv2.IMREAD_COLOR)
img_2 = np.copy(img)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_,img_thr = cv2.threshold(img_gray, 0, 255, cv2.THRESH_OTSU)
cv2.imshow('thr', img_thr)

contours, _ = cv2.findContours(img_thr, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for i in range(len(contours)):
    if cv2.contourArea(contours[i]) < 100:  #  너무 작으면 무시
        continue
    cv2.drawContours(img, contours, i, (0,0,255), 2)
    pos = (contours[i][0][0][0], contours[i][0][0][1]-7)
    cv2.putText(img, str(i), pos, cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255),3)

cv2.drawContours(img_2, contours, 247, (0,0,255), 4)
    
    
cv2.imshow('img', img)
cv2.imshow('img2', img_2)
cv2.waitKey()
cv2.destroyAllWindows()

In [61]:
#마우스이벤트로 해보겠다
import cv2

mouse_is_pressing = False
start_x, start_y = -1, -1

def mouse_callback(event, x, y, flags, param):
    global start_x, start_y, mouse_is_pressing, img
    
    if event == cv2.EVENT_LBUTTONDOWN:
        mouse_is_pressing = True
        start_x, start_y = x, y
        cv2.circle(img, (x,y), 10, (0,255,0), -1)
        cv2.imshow('img',img)
        
    elif event == cv2.EVENT_LBUTTONUP:
        mouse_is_pressing = False
        cv2.rectangle(img, (start_x, start_y), (x, y), (0,255,0), 3)
        cv2.imshow('img',img)
        img = cv2.imread('basketball.jpg', cv2.IMREAD_COLOR)    


img = cv2.imread('basketball.jpg', cv2.IMREAD_COLOR)    
while True:
    cv2.setMouseCallback('img', mouse_callback)
    key = cv2.waitKey()
    if key == ord('i'):
        img = cv2.pyrDown(img)
        
    
    cv2.imshow('img',img)
    if key == 27:
        break

cv2.destroyAllWindows()

회전 

In [49]:
import cv2

src = cv2.imread('banana.jpg')
cp = (src.shape[1]/2, src.shape[0]/2) #(x,y)

print(cp)
rot1 = cv2.getRotationMatrix2D(cp,45,1)
dst1 = cv2.warpAffine(src, rot1, (0,0))

cv2.imshow('src', src)
cv2.imshow('dst1', dst1)

cv2.waitKey()
cv2.destroyAllWindows()


(150.0, 136.5)


## 이미지변환

affine transform

In [65]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('banana.jpg')
rows, cols = img.shape[:2]

#변환 전후 각 좌표 3개 생성
pts1 = np.float32([[100,50],[200,100],[100,200]])
pts2 = np.float32([[80,70],[210,60],[250,120]])

#변환 전 좌표 이미지에 표시
cv2.circle(img, (100,50), 5, (255,0,0), -1)
cv2.circle(img, (200,100), 5, (0,255,0), -1)
cv2.circle(img, (100,200), 5, (255,0), -1)

#변환행렬계산
mtrx = cv2.getAffineTransform(pts1,pts2)

#어떤 변환 적용
dst = cv2.warpAffine(img, mtrx, (int(cols*1.5), rows))

cv2.imshow('img',img)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

perspective transform

In [67]:
import cv2

img = cv2.imread('banana.jpg')
rows, cols = img.shape[:2]

#원본4개의점, 결과4개의점
pts1 = np.float32([[0,0],[0,rows],[cols,0],[cols,rows]])
pts2 = np.float32([[100,50],[10,rows-50],[cols-100,50],[cols-10,rows-50]])

#원본영상에 4개의 점 표시
cv2.circle(img, (0,0), 10, (255,0,0), -1)
cv2.circle(img, (0,rows), 10, (0,255,0),-1)
cv2.circle(img, (cols,0), 10, (0, 0, 255),  -1)
cv2.circle(img, (cols,rows), 10, (0, 255, 255), -1)

#원근 변환 행렬 계산
mtrx = cv2.getPerspectiveTransform(pts1, pts2)

#원근변환적용
dst = cv2.warpPerspective(img, mtrx, (cols, rows))

cv2.imshow('img', img)
cv2.imshow('perspective', dst)

cv2.waitKey()
cv2.destroyAllWindows()

문서 스캐너 실습

In [6]:
import cv2
import numpy as np

pt = []
img = cv2.imread('paper.jpg')
img_copy = img.copy()

def mouse_fn(event, x, y, flags, param): 
    global pt, rows, cols, img
    
    if event == cv2.EVENT_LBUTTONDOWN: 
        print('success')
        cv2.circle(img, (x,y), 10, (0,255,0), -1) 
        cv2.imshow('img',img)
        pt.append([x,y])
        print(pt)
        if len(pt) >=  4:
            cv2.putText(img,'!all points are drawed!',(int(cols/2)-50,int(rows/2)) , cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))
            cv2.imshow('img',img)

while True:
    rows, cols = img.shape[:2]
    pts2 = np.float32([[0,0],[cols,0],[0,rows],[cols,rows]])

    cv2.namedWindow('img')

    cv2.setMouseCallback('img', mouse_fn)
    cv2.imshow('img',img)

    key = cv2.waitKey() 
    if key == ord('c'):
        pt =  np.float32(pt)
        #원근 변환 행렬 계산
        mtrx = cv2.getPerspectiveTransform(pt, pts2)
        #원근변환적용
        dst = cv2.warpPerspective(img_copy, mtrx, (cols, rows))
        dst_gray = cv2.cvtColor(dst, cv2.COLOR_BGR2GRAY)
        scan = cv2.adaptiveThreshold(dst_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 21, 10)
        cv2.imshow('scan',scan)
    elif key == 27:
        break

cv2.destroyAllWindows()

success
[[51, 55]]
success
[[51, 55], [437, 67]]
success
[[51, 55], [437, 67], [57, 632]]
success
[[51, 55], [437, 67], [57, 632], [432, 621]]


기본 미분필터

In [19]:
import cv2
import numpy as np

img = cv2.imread('sudoku.jpg')
rows, cols = img.shape[:2]
#img.resize(int(0.7*rows),int(0.7*cols))


x_kernel = np.array([[1,0],[0,-1]])
y_kernel = np.array([[0,1],[-1, 0]])

edge_gx = cv2.filter2D(img, -1, x_kernel)
edge_gy = cv2.filter2D(img, -1, y_kernel)

merged = np.hstack((edge_gx, edge_gy, (edge_gx+edge_gy)))

cv2.imshow('edge', merged)
cv2.waitKey()
cv2.destroyAllWindows()

kernel종류별로 kernel값을 변경하며 진행하면 된다.

In [7]:
#Sobel 미분 필터
import cv2
import numpy as np

src = cv2.imread('lenna.jpg', cv2.IMREAD_GRAYSCALE)

dx = cv2.Sobel(src, cv2.CV_32F, 1, 0)
dy = cv2.Sobel(src, cv2.CV_32F, 0, 1)

mag = cv2.magnitude(dx, dy)
mag = np.clip(mag,0,255).astype(np.uint8)# clip()함수: (배열, 최솟값기준, 최댓값기준)이 범위 벗어나는 수들 최소,최댓값으로 대체

cv2.imshow('src', src)
cv2.imshow('dx',dx)
cv2.imshow('dy', dy)
cv2.imshow('sobel',dx+dy)
cv2.imshow('mag',mag)

cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#canny 
import cv2
import numpy as np

src = cv2.imread('lenna.jpg', cv2.IMREAD_GRAYSCALE)

edge = cv2.Canny(src, 10, 127)
edge2 = cv2.Canny(src, 64, 127)

cv2.imshow('ori', src)
cv2.imshow('edge', edge)
cv2.imshow('edge_64_127', edge2)

cv2.waitKey()
cv2.destroyAllWindows()

실시간 영상에 엣지 표시하기

In [3]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH,320)
cap.set(cv2.CAP_PROP_FRAME_WIDTH,240)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
        
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    edge = cv2.Canny(frame_gray, 80, 127)
    
    edge1 = cv2.bitwise_not(edge)
    edge1 = cv2.cvtColor(edge1,cv2.COLOR_GRAY2BGR)
    edge = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)
    
    img1 = cv2.bitwise_and(frame, edge1)
    img2 = cv2.bitwise_and(frame, edge)
    
    merged = np.hstack((frame, img2, img1))
    
    cv2.imshow('edge Camera', merged)
        
    if cv2.waitKey(1)==27:
        break

cap.release()
cv2.destroyAllWindows()

외곽선검출과 오일페인팅 효과

In [1]:
import cv2
import numpy as np
def onChangeThresh1(val):
    global thresh1, thresh2
    thresh1=val
    print('thresh1, thresh2 =', thresh1, thresh2)
    edge = cv2.Canny(img, thresh1, thresh2)
    cv2.imshow('edge', edge)

def onChangeThresh2(val):
    global thresh1, thresh2
    thresh2=val
    print('thresh1, thresh2 =', thresh1, thresh2)
    edge = cv2.Canny(img, thresh1, thresh2)
    cv2.imshow('edge', edge)

img = cv2.imread('edge_test1.jpg',cv2.IMREAD_COLOR)

thresh1 = 50
thresh2 = 120

cv2.namedWindow('edge')
cv2.createTrackbar('thresh1', 'edge', thresh1, 255, onChangeThresh1)
cv2.createTrackbar('thresh2', 'edge', thresh2, 255, onChangeThresh2)

edge = cv2.Canny(img, thresh1, thresh2)

cv2.imshow('img', img)
cv2.imshow('edge', edge)
cv2.waitKey()
cv2.destroyAllWindows()

thresh1, thresh2 = 101 120
thresh1, thresh2 = 50 120
thresh1, thresh2 = 50 171
thresh1, thresh2 = 101 171
thresh1, thresh2 = 101 222
thresh1, thresh2 = 101 255
thresh1, thresh2 = 152 255
thresh1, thresh2 = 101 255
thresh1, thresh2 = 50 255
thresh1, thresh2 = 50 204
thresh1, thresh2 = 50 153
thresh1, thresh2 = 50 102
thresh1, thresh2 = 50 153
thresh1, thresh2 = 50 102
thresh1, thresh2 = 50 153
thresh1, thresh2 = 50 152
thresh1, thresh2 = 50 150
thresh1, thresh2 = 50 149
thresh1, thresh2 = 50 147
thresh1, thresh2 = 50 146
thresh1, thresh2 = 50 144
thresh1, thresh2 = 50 143
thresh1, thresh2 = 50 142
thresh1, thresh2 = 50 140
thresh1, thresh2 = 50 139
thresh1, thresh2 = 50 137
thresh1, thresh2 = 50 136
thresh1, thresh2 = 50 134
thresh1, thresh2 = 50 133
thresh1, thresh2 = 50 131
thresh1, thresh2 = 50 130
thresh1, thresh2 = 50 128
thresh1, thresh2 = 50 127
thresh1, thresh2 = 50 125
thresh1, thresh2 = 50 127
thresh1, thresh2 = 50 128
thresh1, thresh2 = 50 130
thresh1, thresh2 = 50 131
thresh

thresh1, thresh2 = 37 212
thresh1, thresh2 = 37 211
thresh1, thresh2 = 37 209
thresh1, thresh2 = 37 208
thresh1, thresh2 = 37 206
thresh1, thresh2 = 37 205
thresh1, thresh2 = 37 203
thresh1, thresh2 = 37 202
thresh1, thresh2 = 37 200


In [5]:
import cv2
import numpy as np

def oil_painting_effect(src, radius, levels):
    dst = np.zeros(src.shape, src.dtype)
    gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
    
    for i in range(src.shape[0]):
        print(i)
        for j in range(src.shape[1]):
            hist = np.zeros(levels)# 이웃픽셀들 히스토그램 저장 변수
            bgr_sum = np.zeros((levels,3))# 이웃 픽셀들 컬러값 합 저장
            
            # 이웃 픽셀 모두 방문하며 히스토그램과 컬러합계산
            for u in range(max(i-radius,0), min((i+radius+1), src.shape[0])):
                for v in range(max(j-radius,0), min(j+radius+1, src.shape[1])):
                    #해당 히스토그램상자 인덱스 계산
                    level = gray[u,v] * levels//256
                    hist[level] += 1# 히스토그램 누적
                    bgr_sum[level] += src[u,v]
                    
            max_idx = np.argmax(hist) # 히스토그램 값 가장 큰 인덱스
            # 가장 많은 픽셀 속한 히스토그램 구간에 있는 픽셀 평균 컬러 값
            dst[i,j] = bgr_sum[max_idx]//hist[max_idx]
    
    return dst    
            
img = cv2.imread('red-and-green-leavs-of-autumn-jpg.jpg')

radius, levels = 4, 8
effect = oil_painting_effect(img, radius, levels)
cv2.imshow('img', img)
cv2.imshow('effect',effect)
cv2.waitKey()
cv2.destroyAllWindows()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27