## Binarization  

Video expressed only in 0 and 1  
The outline of the shape becomes clear

In [5]:
import cv2
import numpy as np

#read image as grayscale
lenna = cv2.imread('lenna.jpg', cv2.IMREAD_GRAYSCALE)

#binarization in different threshold type
ret, lenna_binary = cv2.threshold(lenna, 150, 255, cv2.THRESH_BINARY)
ret, lenna_bi_inv = cv2.threshold(lenna, 150, 255, cv2.THRESH_BINARY_INV)
ret, lenna_trunc = cv2.threshold(lenna, 150, 255, cv2.THRESH_TRUNC)
ret, lenna_tozero = cv2.threshold(lenna, 150, 255, cv2.THRESH_TOZERO)
ret, lenna_toz_inv = cv2.threshold(lenna, 150, 255, cv2.THRESH_TOZERO_INV)

cv2.imshow('lenna', lenna)
#show images
cv2.imshow('binary', lenna_binary)
cv2.imshow('binary_inv', lenna_bi_inv)
cv2.imshow('trunc', lenna_trunc)
cv2.imshow('tozero', lenna_tozero)
cv2.imshow('tozero_inv', lenna_toz_inv)

cv2.waitKey()
cv2.destroyAllWindows()

adaptive threshold binarization

In [36]:
import cv2

hepburn = cv2.imread('hepburn.jpg', cv2.IMREAD_GRAYSCALE)
hepburn_mean = cv2.adaptiveThreshold(hepburn, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 31, 10)
cv2.imshow('mean_tozero', hepburn_mean)
    
cv2.waitKey()
cv2.destroyAllWindows()

find optimal blocksize with trackbar  
밑의 코드들 -> 트랙바 값에 따라 이미지가 변하지 않았다. 왜?

In [44]:
import cv2
import numpy as np

#trackbar call back function
def adaptive_binarization(pos):
    global hepburn_mean
    block_size = 2*pos +1
    hepburn_mean = cv2.adaptiveThreshold(hepburn_mean, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, block_size, 10)
    print('keep going')
    cv2.imshow('mean_tozero', hepburn_mean)
    
def adaptive_binarization_2(pos):
    global hepburn_gaussian
    block_size = 2*pos +1
    hepburn_gaussian = cv2.adaptiveThreshold(hepburn_gaussian, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, block_size, 10)
    print('keep going')
    cv2.imshow('gaussian_tozero', hepburn_gaussian)

hepburn = cv2.imread('hepburn.jpg', cv2.IMREAD_GRAYSCALE)
hepburn_mean = np.copy(hepburn)
hepburn_gaussian = np.copy(hepburn)

cv2.namedWindow('mean_tozero')#create window for trackbar
cv2.namedWindow('gaussian_tozero')

cv2.createTrackbar('block_size', 'mean_tozero', 1, 15, adaptive_binarization)
cv2.createTrackbar('block_size', 'gaussian_tozero', 1, 15, adaptive_binarization_2)

    
while True:
    cv2.imshow('mean_tozero', hepburn_mean)
    cv2.imshow('gaussian_tozero', hepburn_gaussian)
    
    if cv2.waitKey() == 27:
        break
        
cv2.destroyAllWindows()

keep going
keep going


In [45]:
import cv2
import numpy as np

#trackbar call back function
def nothing(pos):
    print('pass')
    pass

#original images
hepburn = cv2.imread('hepburn.jpg', cv2.IMREAD_GRAYSCALE)
hepburn_mean = np.copy(hepburn)
hepburn_gaussian = np.copy(hepburn)

#create windows
cv2.namedWindow('mean_tozero')#create window for trackbar
cv2.namedWindow('gaussian_tozero')

#create trackbars
cv2.createTrackbar('block_size', 'mean_tozero', 1, 15, nothing)
cv2.createTrackbar('block_size', 'gaussian_tozero', 1, 15, nothing)

while True:
    cv2.imshow('mean_tozero', hepburn_mean)
    cv2.imshow('gaussian_tozero', hepburn_gaussian)
    
    key = cv2.waitKey(1)
    if key == 27:
        break
         
    hepburn_mean = cv2.adaptiveThreshold(hepburn_mean, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, cv2.getTrackbarPos('block_size', 'mean_tozero') * 2 + 1, 10)
    hepburn_gaussian = cv2.adaptiveThreshold(hepburn_gaussian, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, cv2.getTrackbarPos('block_size', 'gaussian_tozero')* 2 + 1, 10)
    
    cv2.imshow('mean_tozero', hepburn_mean)
    cv2.imshow('gaussian_tozero', hepburn_gaussian)
    
    
cv2.destroyAllWindows()

pass
pass
pass
pass
pass
pass
pass
pass
pass


### contour  
cv2.findContours / drawcontours draw contours at original image

In [21]:
import cv2

#original color image and gray image
world_map = cv2.imread('worldmap.jpg', cv2.IMREAD_COLOR)
world_gray = cv2.cvtColor(world_map, cv2.COLOR_BGR2GRAY)

#binarization with gray image
_, img_thresh = cv2.threshold(world_gray, 150, 255, cv2.THRESH_BINARY)

#find contours
contours, hierarchy = cv2.findContours(img_thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#draw contours at original color image in green
#for c in range(len(contours)):
    #draw contour in thickness 1
 #   cv2.drawContours(world_map, contours, c,(0, 255, 0), 1)

#draw contours at original color image in green
cv2.drawContours(world_map, contours, -1 ,(0, 255, 0), 1)

cv2.imshow('map', world_map)

cv2.waitKey()
cv2.destroyAllWindows()

[[[   1   -1   -1   -1]
  [   2    0   -1   -1]
  [   3    1   -1   -1]
  ...
  [1154 1152   -1    6]
  [1155 1153   -1    6]
  [  -1 1154   -1    6]]]


In [20]:
import cv2
import numpy as np

img = np.zeros((480,640, 3), np.uint8)
cv2.circle(img, (200, 150), 80, (255, 255, 0), -1)
cv2.circle(img, (500, 150), 50, (255, 0, 0), -1)
cv2.rectangle(img, (300,300), (500, 400), (0, 255, 255),-1)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#binarization
_, img_thresh = cv2.threshold(img_gray, 150, 255, cv2.THRESH_BINARY)

#simply calculate contour구함
contours, _ = cv2.findContours(img_thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    print(c.shape, c.dtype, cv2.contourArea(c)) #cv2.contourArea(c)=contour면적
    print(c)
#0번째contour의 2번째 점의 x, y좌표
print(contours[0][2][0][0], contours[0][2][0][1])
colors = [(0, 255, 0),(0, 0, 255)]

for c in range(len(contours)):
    #선의 두께 3으로 c번째 contour 그림
    cv2.drawContours(img, contours, c, colors[c], 3)
    
cv2.imshow('img', img)
cv2.imshow('img_gray', img_gray)
cv2.imshow('img_thresh', img_thresh)
cv2.waitKey()
cv2.destroyAllWindows()

(4, 1, 2) int32 20000.0
[[[300 300]]

 [[300 400]]

 [[500 400]]

 [[500 300]]]
(244, 1, 2) int32 19854.0
[[[200  70]]

 [[199  71]]

 [[188  71]]

 [[187  72]]

 [[183  72]]

 [[182  73]]

 [[179  73]]

 [[178  74]]

 [[176  74]]

 [[175  75]]

 [[173  75]]

 [[172  76]]

 [[170  76]]

 [[169  77]]

 [[168  77]]

 [[167  78]]

 [[166  78]]

 [[165  79]]

 [[164  79]]

 [[163  80]]

 [[162  80]]

 [[161  81]]

 [[160  81]]

 [[159  82]]

 [[158  82]]

 [[156  84]]

 [[155  84]]

 [[153  86]]

 [[152  86]]

 [[147  91]]

 [[146  91]]

 [[141  96]]

 [[141  97]]

 [[136 102]]

 [[136 103]]

 [[134 105]]

 [[134 106]]

 [[132 108]]

 [[132 109]]

 [[131 110]]

 [[131 111]]

 [[130 112]]

 [[130 113]]

 [[129 114]]

 [[129 115]]

 [[128 116]]

 [[128 117]]

 [[127 118]]

 [[127 119]]

 [[126 120]]

 [[126 122]]

 [[125 123]]

 [[125 125]]

 [[124 126]]

 [[124 128]]

 [[123 129]]

 [[123 132]]

 [[122 133]]

 [[122 137]]

 [[121 138]]

 [[121 149]]

 [[120 150]]

 [[121 151]]

 [[121 162]]

In [31]:
import cv2
import numpy as np

img = np.zeros((480,640, 3), np.uint8)
cv2.rectangle(img, (240,40), (400, 440), (255, 255, 255),-1)
cv2.rectangle(img, (440,40), (600, 440), (255, 255, 255),-1)
cv2.rectangle(img, ( 80,120), (160, 200), (0, 0, 0),-1)
cv2.rectangle(img, ( 80,280), (160, 360), (0, 0, 0),-1)
cv2.rectangle(img, (270, 70), (370, 410), (0, 0, 0),-1)
cv2.rectangle(img, (300,120), (340, 160), (255, 255, 255),-1)
cv2.rectangle(img, (300,220), (340, 260), (255, 255, 255),-1)
cv2.rectangle(img, (300,320), (340, 360), (255, 255, 255),-1)
cv2.imshow('img',img)
cv2.waitKey()

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#binarization이미 되어있는 이미지라서 생략
#_, img_thresh = cv2.threshold(img_gray, 150, 255, cv2.THRESH_BINARY)

#simply calculate contour구함
contours, hierarchy = cv2.findContours(img_gray, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

print('number of contours :',len(contours))
print('hierarchy',hierarchy.shape)
for i in range(hierarchy.shape[1]):
    print(i, hierarchy[0][i])

print(hierarchy)
colors = [(0, 0, 255), (0, 255, 0),(255, 0, 0), (0,255, 255), (255, 0, 255), (255, 255, 0), (0, 0, 255), (0, 255, 0), (255, 0, 0)]
for i in range(len(contours)):
    #선의 두께 3으로 c번째 contour 그림
    cv2.drawContours(img, contours, i, colors[i], 3)
    #contour첫번째점위치보다약간위좌표에숫자출력
    pos = contours[i][0][0][0], contours[i][0][0][1]-7
    cv2.putText(img, str(i), pos, cv2.FONT_HERSHEY_SIMPLEX, 1.2, colors[i], 3)
    
cv2.imshow('img', img)

cv2.waitKey()
cv2.destroyAllWindows()

number of contours : 6
hierarchy (1, 6, 4)
0 [ 1 -1 -1 -1]
1 [-1  0  2 -1]
2 [-1 -1  3  1]
3 [ 4 -1 -1  2]
4 [ 5  3 -1  2]
5 [-1  4 -1  2]
[[[ 1 -1 -1 -1]
  [-1  0  2 -1]
  [-1 -1  3  1]
  [ 4 -1 -1  2]
  [ 5  3 -1  2]
  [-1  4 -1  2]]]


find contours and detect figures 

In [43]:
import cv2
import numpy as np

img = cv2.imread('figures.jpg', cv2.IMREAD_COLOR)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#binarization 
_, thresh_img = cv2.threshold(img_gray, 250, 255, cv2.THRESH_BINARY)
#find contour
contours, hierarchy = cv2.findContours(thresh_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

for i in range(len(contours)):
    #선의 두께 3으로 c번째 contour 그림
    cv2.drawContours(img, contours, i, (0,0,0), 3)
    #contour첫좌표조금위에순서출력
    pos = contours[i][0][0][0], contours[i][0][0][1]+7
    cv2.putText(img, str(i), pos, cv2.FONT_HERSHEY_SIMPLEX, 1.2, (0,0,0), 3)

cv2.imshow('thres',thresh_img)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [47]:
import cv2
import numpy as np

img = cv2.imread('figures.jpg', cv2.IMREAD_COLOR)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#binarization 
_, thresh_img = cv2.threshold(img_gray, 250, 255, cv2.THRESH_BINARY)
#find contour
contours, hierarchy = cv2.findContours(thresh_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#근사화 사용해서 출력해보기
for cnt in contours:
    epsilon = 0.02*cv2.arcLength(cnt, True)
    approx = cv2.approxPolyDP(cnt, epsilon, True)
    cv2.drawContours(img, [approx], 0,(0,0,0), 3)

cv2.imshow('thres',thresh_img)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

cv2.isContourConvex(contour): contour가 convex인지 아닌지 판단하여 True 또는 False를 Return합니다. 여기서 convex란 contour line이 볼록하거나 최소한 평평한 것을 의미합니다.(오목한 부분이 없는 것입니다.)

In [52]:
import cv2

arc = cv2.imread('arc_length.jpg', cv2.IMREAD_COLOR)
arc_gray = cv2.cvtColor(arc, cv2.COLOR_BGR2GRAY)

_, thresh_img = cv2.threshold(arc_gray, 200, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(thresh_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

cv2.drawContours(arc, contours, -1 ,(0, 255, 0), 1)
print('convex?'cv2.isContourConvex(contours[0]))
print('contour length:',len(contours))
print('contour ')
cv2.imshow('arc', arc)

cv2.waitKey()
cv2.destroyAllWindows()

True


도형 읽고 라벨링

In [2]:
#fruit 이미지에 외곽선 그리기
import random 
import numpy as np
import cv2

src = cv2.imread('fruit.jpg', cv2.IMREAD_GRAYSCALE)

_, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_OTSU)
contours, _ = cv2.findContours(src_bin, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

h, w = src.shape[:2]
dst = np.zeros((h, w, 3), np.uint8)

#contours에서 추출한 외곽선 좌표 직접 그리기
for i in range(len(contours)):
    color = (random.randint(0,255), random.randint(0, 255), random.randint(0, 255))
    cv2.drawContours(dst, contours, i, color, 1, cv2.LINE_AA)
    
cv2.imshow('src', src)
cv2.imshow('src_bin', src_bin)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
#카메라 영상에서 움직임이 있는 곳에 박스치기
import cv2
import numpy as np

#감도 설정(카메라 품질 따라 조정이 필요하다)
thresh = 25#달라진 픽셀값 기준치
max_diff = 5 #달라진 픽셀 갯수 기준치

#카메라 캡션 장치 준비
a, b, c = None, None, None
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640) #폭설정
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480) #높이 설정

if cap.isOpened():
    ret, a = cap.read() #a frame 읽고
    ret, b = cap.read() #b frame 읽고
    
    while ret:
        ret, c = cap.read() #c frame 읽어
        draw = c.copy() #출력 영상에 사용할 복제본
        if not ret:
            break
        
        #영상 grayscale변경
        a_gray = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        b_gray = cv2.cvtColor(b, cv2.COLOR_BGR2GRAY)
        c_gray = cv2.cvtColor(c, cv2.COLOR_BGR2GRAY)
    
        #a-b, b-c 절댓값차이
        diff1 = cv2.absdiff(a_gray, b_gray)
        diff2 = cv2.absdiff(a_gray, c_gray)
        
        #threshold값 미만의 차이는 무시
        ret, diff1_t = cv2.threshold(diff1, thresh, 255, cv2.THRESH_BINARY)
        ret, diff2_t = cv2.threshold(diff2, thresh, 255, cv2.THRESH_BINARY)
        
        #두 차이에 대해 AND연산. 두 영상에서 차이가 모두 발견된 경우를 찾는다
        diff = cv2.bitwise_and(diff1_t, diff2_t)
        
        #opening으로 노이즈 제거
        k = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))
        diff  = cv2.morphologyEx(diff, cv2.MORPH_OPEN, k)
        
        #차이 발생 픽셀 갯수 판단 후 사각형
        diff_cnt = cv2.countNonZero(diff)
        if diff_cnt > max_diff :
            nzero = np.nonzero(diff)#0아닌 픽셀의 좌표 얻기
            cv2.rectangle(draw, (min(nzero[1]), min(nzero[0])), (max(nzero[1]), max(nzero[0])), (0, 255, 0),2)
            cv2.putText(draw, 'Motion Detected', (10, 30), cv2.FONT_HERSHEY_DUPLEX, 0.5, (0,0,255))
            
        #컬러영상, threshold영상 통합해 출력
        stacked = np.hstack((draw, cv2.cvtColor(diff, cv2.COLOR_GRAY2BGR)))
        cv2.imshow('result', stacked)
        
        #다음 비교를 위해 영상 순서 정리
        a=b
        b=c
        
        if cv2.waitKey(1)==27:
            break
            
cv2.destroyAllWindows()